-- 0001_init: ideas, comments (threaded + anchored), resources.
-- IDs are UUIDv7 generated by the application, so no uuid extension is required here.

create table if not exists ideas (
    id         uuid primary key,
    title      varchar(200) not null,
    body       jsonb        not null default '[]'::jsonb,
    created_at timestamptz  not null default now(),
    updated_at timestamptz  not null default now()
);

create table if not exists comments (
    id           uuid        primary key,
    idea_id      uuid        not null references ideas (id) on delete cascade,
    -- null parent_id marks a thread root; replies cascade with their root.
    parent_id    uuid        references comments (id) on delete cascade,
    -- anchor columns are populated for thread roots only, null for replies.
    block_index  int,
    start_offset int,
    end_offset   int,
    snippet      text,
    body         text        not null,
    status       text        not null default 'open' check (status in ('open', 'resolved')),
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now(),

    -- a row is either a fully anchored root or a fully unanchored reply.
    constraint comments_anchor_shape check (
        (parent_id is null
            and block_index is not null
            and start_offset is not null
            and end_offset is not null
            and snippet is not null)
        or
        (parent_id is not null
            and block_index is null
            and start_offset is null
            and end_offset is null
            and snippet is null)
    ),
    constraint comments_anchor_range check (
        start_offset is null or (start_offset >= 0 and end_offset > start_offset)
    ),
    constraint comments_block_index_range check (block_index is null or block_index >= 0)
);

create index if not exists comments_idea_id_idx on comments (idea_id);
create index if not exists comments_parent_id_idx on comments (parent_id);

create table if not exists resources (
    id         uuid        primary key,
    idea_id    uuid        not null references ideas (id) on delete cascade,
    type       text        not null check (type in ('image', 'link')),
    url        text        not null,
    label      text,
    created_at timestamptz not null default now(),

    -- attaching the same URL twice to one idea is a conflict, not a new resource.
    constraint resources_idea_url_unique unique (idea_id, url)
);

create index if not exists resources_idea_id_idx on resources (idea_id);
