-- 0002_tags_and_links: a shared tag vocabulary, and typed links between ideas.
-- IDs are UUIDv7 generated by the application, matching 0001.

-- Tags are global, not per-idea, so the same concept is one row however many
-- ideas carry it. slug is the case- and punctuation-folded identity used for
-- lookup and uniqueness; name preserves what the user typed.
create table if not exists tags (
    id         uuid        primary key,
    name       varchar(60) not null,
    slug       varchar(60) not null,
    created_at timestamptz not null default now(),

    constraint tags_slug_unique unique (slug),
    constraint tags_slug_nonempty check (slug <> '')
);

create table if not exists idea_tags (
    idea_id    uuid        not null references ideas (id) on delete cascade,
    tag_id     uuid        not null references tags (id) on delete cascade,
    created_at timestamptz not null default now(),

    primary key (idea_id, tag_id)
);

-- Listing an idea's tags walks the primary key; listing a tag's ideas needs
-- its own index because tag_id is the trailing column.
create index if not exists idea_tags_tag_id_idx on idea_tags (tag_id);

-- A link is stored once, directed from source to target. Symmetric relations
-- ('similar', 'related') read the same either way; directed ones
-- ('references', 'expands') are rendered as their inverse on the target.
create table if not exists idea_links (
    id             uuid        primary key,
    source_idea_id uuid        not null references ideas (id) on delete cascade,
    target_idea_id uuid        not null references ideas (id) on delete cascade,
    relation       text        not null check (relation in ('references', 'expands', 'similar', 'related')),
    note           varchar(280),
    created_at     timestamptz not null default now(),

    -- An idea cannot link to itself, and one relation between two ideas is
    -- stated once; a second attempt is a conflict, not a duplicate row.
    constraint idea_links_not_self check (source_idea_id <> target_idea_id),
    constraint idea_links_unique unique (source_idea_id, target_idea_id, relation)
);

create index if not exists idea_links_source_idx on idea_links (source_idea_id);
create index if not exists idea_links_target_idx on idea_links (target_idea_id);
